### ISSUE TITLE
(using vscode, platformio, framework espidf 5.0.1) W (54090) httpd_txrx: httpd_sock_err: error in send : 11

### ISSUE THREAD

**Issue by OsvaldoTCF** [nopnop2002/esp-idf-web-form#3]
On VSCode with Platformio, i get this error when submit anything.

![image](https://github.com/nopnop2002/esp-idf-web-form/assets/5272869/9c5ad7b8-44e6-4e47-b27d-c28f3fba7197)

_ Configuration _
![image](https://github.com/nopnop2002/esp-idf-web-form/assets/5272869/1fd1b616-c9b1-41b0-b547-6d77d0f0c8b7)

**Comment by nopnop2002** [comment]
This project requires esp-idf.
This is not a issues for this project.
This is a picture using ESP-IDF.
![esp-idf-web-form](https://github.com/nopnop2002/esp-idf-web-form/assets/6020549/1bcc9aa2-0fd0-4243-a57a-86526fb3ef92)


This is a platformio issue.
pio does not support all features.
**Many features are unavailable.**
Post your issues here..
https://github.com/espressif/arduino-esp32/issues

**Comment by OsvaldoTCF** [comment]
This is my platformio.ini:

[env:lolin_c3_mini]
platform = espressif32
board = lolin_c3_mini
framework = espidf ; version 5.0.1

I do not use arduino or referenced it.

**Comment by nopnop2002** [comment]
The components that pio uses are separate from the ESP-IDF components.

Very similar, but a different implementation.

I think this setting is not reflected or is disabled or buggy.
```
CONFIG_HTTPD_MAX_REQ_HDR_LEN=1024
```

Post your issues here..
https://github.com/platformio/platformio-core/issues

---

This is the magic of PIO.

At first glance, they appear to use the same core libraries and components.

But it's different.
